#!/bin/bash
#PBS -q workq
#PBS -A hpc_houmicro06
#PBS -l nodes=1:ppn=20
#PBS -l walltime=24:00:00
#PBS -o /work/bmath27/filters/
#PBS -j oe
#PBS -N demux
#PBS -m abe
#PBS -M bmath27@lsu.edu
date

cd /work/bmath27/
unset PYTHONPATH
unset PYTHONUSERBASE
source activate qiime2-2021.11
cd /work/bmath27/filters

#Step1 demultiplexes EMPPairedEndSequences data
#Determine your trim values before running

qiime tools import \
   --type EMPPairedEndSequences \
   --input-path data/raw/Illumina4 \
   --output-path data/qiime/emp-paired-end-sequences.qza

qiime demux emp-paired \
  --m-barcodes-file data/raw/metadata.tsv \
  --m-barcodes-column BarcodeSequence \
  --i-seqs data/qiime/emp-paired-end-sequences.qza \
  --o-per-sample-sequences data/qiime/demux.qza \
  --p-rev-comp-mapping-barcodes \
  --o-error-correction-details data/qiime/demux-details.qza

qiime demux summarize \
  --i-data data/qiime/demux.qza \
  --o-visualization data/qiime/demux.qzv

  qiime dada2 denoise-paired \
  --i-demultiplexed-seqs data/qiime/demux.qza \
  --p-trim-left-f 30 \
  --p-trim-left-r 30 \
  --p-trunc-len-f 250 \
  --p-trunc-len-r 200 \
  --p-n-threads 0 \
  --o-table data/qiime/table.qza \
  --o-representative-sequences data/qiime/rep-seqs.qza \
  --o-denoising-stats data/qiime/denoising-stats.qza
  --verbose
 
 qiime feature-table summarize \
  --i-table data/qiime/table.qza \
  --o-visualization data/qiime/table.qzv \
  --m-sample-metadata-file data/raw/metadata.tsv

qiime feature-table tabulate-seqs \
  --i-data data/qiime/rep-seqs.qza \
  --o-visualization data/qiime/rep-seqs.qzv

  qiime metadata tabulate \
  --m-input-file data/qiime/denoising-stats.qza \
  --o-visualization data/qiime/denoising-stats.qzv
    date
    exit 0
