#!/bin/bash
#PBS -q checkpt
#PBS -A hpc_houmicro06
#PBS -l nodes=1:ppn=20
#PBS -l walltime=0:10:00
#PBS -o /work/bmath27/filters/
#PBS -j oe
#PBS -N diversity
#PBS -m abe
#PBS -M bmath27@lsu.edu
date

cd /work/bmath27/
unset PYTHONPATH
unset PYTHONUSERBASE
source activate qiime2-2021.11
cd /work/bmath27/filters/

#Make directory for core-metrics-results
mkdir /data/process/core-metrics-results/

# Alpha and Beta Diversity Analysis
    #Sampling depth set at minimum frequency since there are only 12 total samples
qiime diversity core-metrics-phylogenetic \
    --i-phylogeny data/qiime/rooted-tree.qza \
    --i-table data/qiime/table.qza \
    --p-sampling-depth 6156 \
    --m-metadata-file data/raw/metadata.tsv \
    --output-dir data/process/core-metrics-results

qiime diversity alpha-group-significance \
        --i-alpha-diversity data/process/core-metrics-results/evenness_vector.qza \
        --m-metadata-file data/raw/metadata.tsv \
        --o-visualization data/process/core-metrics-results/evenness-group-significance.qzv

qiime diversity alpha-group-significance \
        --i-alpha-diversity data/process/core-metrics-results/faith_pd_vector.qza \
        --m-metadata-file data/raw/metadata.tsv \
        --o-visualization data/process/core-metrics-results/faith-pd-group-significance.qzv

qiime diversity beta-group-significance \
	  --i-distance-matrix data/process/core-metrics-results/unweighted_unifrac_distance_matrix.qza \
          --m-metadata-file data/raw/metadata.tsv \
          --m-metadata-column filtration_level \
          --o-visualization data/process/core-metrics-results/unweighted-unifrac-station-significance-filtration.qzv \
          --p-pairwise

qiime diversity beta-group-significance \
          --i-distance-matrix data/process/core-metrics-results/unweighted_unifrac_distance_matrix.qza \
          --m-metadata-file data/raw/metadata.tsv \
          --m-metadata-column time_point \
          --o-visualization data/process/core-metrics-results/unweighted-unifrac-station-significance-time.qzv \
          --p-pairwise

# Ordination by volume
qiime emperor plot \
  --i-pcoa data/process/core-metrics-results/unweighted_unifrac_pcoa_results.qza \
  --m-metadata-file data/raw/metadata.tsv \
  --p-custom-axes volume(ml) \
  --o-visualization data/process/core-metrics-results/unweighted-unifrac-emperor-volume.qzv

qiime emperor plot \
  --i-pcoa data/process/core-metrics-results/bray_curtis_pcoa_results.qza \
  --m-metadata-file data/raw/metadata.tsv \
  --p-custom-axes volume(ml) \
  --o-visualization data/process/core-metrics-results/bray-curtis-emperor-days-volume.qzv

# Ordination by filter time
qiime emperor plot \
  --i-pcoa data/process/core-metrics-results/unweighted_unifrac_pcoa_results.qza \
  --m-metadata-file data/raw/metadata.tsv \
  --p-custom-axes filter_time(hr) \
  --o-visualization data/process/core-metrics-results/unweighted-unifrac-emperor-time.qzv

qiime emperor plot \
  --i-pcoa data/process/core-metrics-results/bray_curtis_pcoa_results.qza \
  --m-metadata-file data/raw/metadata.tsv \
  --p-custom-axes filter_time(hr) \
  --o-visualization data/process/core-metrics-results/bray-curtis-emperor-days-time.qzv

#Alpha Rarefaction Plotting
	# * Choose max depth based on median frequency per sample value in table.qzv file
  #Chose based on max frequency due to there only being 12 samples
qiime diversity alpha-rarefaction \
  --i-table data/qiime/table.qza \
  --i-phylogeny data/qiime/rooted-tree.qza \
  --p-max-depth 16353 \
  --m-metadata-file data/raw/metadata.tsv \
  --o-visualization data/process/alpha-rarefaction.qzv

date
exit 0
