#!/bin/bash
#PBS -q workq
#PBS -A hpc_houmicro06
#PBS -l nodes=1:ppn=20
#PBS -l walltime=2:00:00
#PBS -o /work/bmath27/filters/
#PBS -j oe
#PBS -N phytree
#PBS -m abe
#PBS -M bmath27@lsu.edu
date

cd /work/bmath27/
unset PYTHONPATH
unset PYTHONUSERBASE
source activate qiime2-2021.11
cd /work/bmath27/filters

###############################################################

# Diversity analysis
#Generate a tree for phylogenetic diversity analyses
qiime alignment mafft \
  --i-sequences data/qiime/rep-seqs.qza \
  --o-alignment data/qiime/aligned-rep-seqs.qza
  qiime alignment mask \
    --i-alignment data/qiime/aligned-rep-seqs.qza \
    --o-masked-alignment data/qiime/masked-aligned-rep-seqs.qza
    qiime phylogeny fasttree \
      --i-alignment data/qiime/masked-aligned-rep-seqs.qza \
      --o-tree data/qiime/unrooted-tree.qza
      qiime phylogeny midpoint-root \
        --i-tree data/qiime/unrooted-tree.qza \
        --o-rooted-tree data/qiime/rooted-tree.qza

date
exit 0
